# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'strikethrough', 'superscript', 'with_toc_data']

# Permalinks
# permalink:        pretty
permalink: /blog/:year/:month/:day/:title

# Setup
title:            'Andrew Aguiar'
tagline:          'Software developer'
description:      'Software developer and development instructor'

url:             https://www.andrewsaguiar.com/
url_pure:        https://www.andrewsaguiar.com
assets_base_url: https://www.andrewsaguiar.com/assets/

author:
  name:           'Andrew S Aguiar'
  url:            https://br.linkedin.com/in/andrewaguiar

paginate:         20

# Custom vars
version:          2.1.0

github:
  url:           https://github.com/andrewaguiar

linkedin:
  url:           https://br.linkedin.com/in/andrewaguiar

comments: false

baseurl: '/'

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

compress_html:
  clippings: [all]
